### PR TITLE
added vdv_radii up to 99 and spica cg particles to data.py

### PR DESCRIPTION
**Pull request by alphataubio**
SOURCES:
- https://pubchem.ncbi.nlm.nih.gov/periodic-table/
- https://github.com/SPICA-group/spica-tools/blob/main/src/gen_top_ENM.py

```
from gen_top_ENM import bb, bd_mass
i = 1000

for particle in sorted(bd_mass.keys()):
  if( particle in bb ):
    for suffix in ['','L','S','N','P']:
      print( "    " + "\"{0}\":{{\"atomic_number\":{1},\"vdw_radii\":99,\"name\":\"{0}\",\"standard_mass\":{2}}},".format(particle+suffix,i,bd_mass[particle]))
      i += 1
  else:
    print( "    " + "\"{0}\":{{\"atomic_number\":{1},\"vdw_radii\":99,\"name\":\"{0}\",\"standard_mass\":{2}}},".format(particle,i,bd_mass[particle]))
    i += 1

print( "\n\n" )
i = 1000

for particle in sorted(bd_mass.keys()):
  if( particle in bb ):
    for suffix in ['','L','S','N','P']:
      print( "    " + "{0}:{{\"element_symbol\":\"{1}\",\"name\":\"{1}\",\"standard_mass\":{2},\"vdw_radii\":99}},".format(i, particle+suffix, bd_mass[particle]))
      i += 1
  else:
    print( "    " + "{0}:{{\"element_symbol\":\"{1}\",\"name\":\"{1}\",\"standard_mass\":{2},\"vdw_radii\":99}},".format(i, particle, bd_mass[particle]))
    i += 1
```

### CODE REVIEW

**Comment by rbdavid** [comment]
So, your first commit to your fork added all of the values you wanted to include. Great! But then your second commit undid all that work.  If you are worried about maintaining formatting, you can recreate that using the `json` module:

```python
import json
import molecularnodes as mn

# grab the elements dictionary
elements_dict = mn.data.elements
# grab the elements_by_atomic_number dictionary
elements_by_atomic_number_dict = mn.data.elements_by_atomic_number

# make your changes to both dicts

with open('some_temp_file.json','w') as json_out:
    json.dump(elements_dict,json_out, indent = 4)
with open('some_temp_file2.json','w') as json_out:
    json.dump(elements_by_atomic_number_dict,json_out,indent=4)
```

Then just copy and paste the lines from those files into the `data.py` file, replacing the old dictionaries.

**Comment by rbdavid** [comment]
As far as I can tell, the one check failing is not associated with the changes you are making here. Its also failing for my PR request that band-aids this problem.

**Comment by rbdavid** [comment]
Oh, also, consider using a larger default vdw_radii value for your CG particles. 99 pm is smaller than any of the elements' vdw radii. But your particles are a combination of multiple atoms, so the default should be much larger, in my opinion. In fact, depending on how bonds are assigned/predicted, a ball-and-stick representation may just show spheres floating in space with no bonds between particles. If I recall correctly, if your topology file doesn't define bonds explicitly,

**Comment by alphataubio** [comment]
i had a problem with the zip file created by build getting committed, im closing this pull request and restarting from scratch

**Comment by BradyAJohnston** [comment]
Thanks @rbdavid for giving feedback, I think you've got the right idea for this. I'm away for another 2 weeks hiking so won't be able to review / merge until then (might get a chance earlier)

**Comment by rbdavid** [comment]
Enjoy your vacation, Brady!

**Comment by alphataubio** [comment]
> Thanks @rbdavid for giving feedback, I think you've got the right idea for this. I'm away for another 2 weeks hiking so won't be able to review / merge until then (might get a chance earlier)

@BradyAJohnston... athletes need time to recover, so do you to get back even stronger. no rush at all, im only starting to play around with MN, possibly teaching it as part as a module on scientific visualization for an undergrad bioinformatics course in sept 2024 or jan 2025.

my eventual goal is to "backmap" coarse-grained SPICA and CGDNA (aka oxDNA) trajectories from LAMMPS simulations using cartoons for protein secondary structure and atoms for side chains, together with transparent molecular surface computed using MSMS.

@rbdavid has been doing a fine job holding down the fort in your absence.

**Comment by BradyAJohnston** [comment]
I'm now back - did you want to recreate the PR with the updated values?

**Comment by BradyAJohnston** [comment]
Very interested to know more about this course on scientific visualisation as well. Would love to know how MN / Blender is being used.

**Comment by alphataubio** [comment]
> Very interested to know more about this course on scientific visualisation as well. Would love to know how MN / Blender is being used.

it's only at the proposal/draft stage now, might not be offered until september 2025 if at all. it's a special topics course on bioinformatics:

"An elective course created for students interested in Bioinformatics. Topics include installing open source software, reading documentation, R, Python, scientific visualization, and bioinformatics databases, together with a discussion of common errors in statistics and how students can avoid them in their research and publications."

"By the end of the course, students should be able to:
- Install and use open source software commonly used in bioinformatics.
- Have a basic understanding of R and python to write their own code using available packages.
- Prepare 2D and 3D visualizations of the subject(s) of interest.
- Access online bioinformatics databases.
- Apply good statistical methodology in their research, and recognize poor statistical practices in the literature.
- Critically evaluate and replicate recent bioinformatics literature, or apply bioinformatics methods in their own research."

that's why i was starting to look at MN as a potential 1-2 weeks module of a 12 weeks course.

**Pull request closed without merging**
