### PR TITLE
Added Discord href to README.md

### PR DESCRIPTION
**Pull request by hwcopeland**
Added Discord href to README.md

### CODE REVIEW

**Comment by BradyAJohnston** [comment]
Ah thanks! Does this link expire?

**Comment by hwcopeland** [comment]
No It just didn't have a link haha. Had to go googling to find the link. Figured I'd issue a pull and add it. I pulled that link from reddit I think and it still works.

**Comment by BradyAJohnston** [comment]
I'll add a permanent link and in there then!

**Comment by hwcopeland** [comment]
Great will do. Sorry for delayed response. Was making an introduction post in discord and somehow rabbitholed to extending a vms storage.

**Pull request merged**
