### PR TITLE
intiial support for CryoEM `.map` import in Blender 3.5

### PR DESCRIPTION
**Pull request by BradyAJohnston**
Blender 3.5 (currently in Beta, to be released in late March) packages `pyopenvdb` package allowing for the handling of CryoEM density, and potentially X-ray crystallography electron density.

Currently this is a working example of how to import the CryoEM `.map` data, save it as a `.vdb` and then import that `.vdb` into Blender.

Following the [tutorial](https://www.youtube.com/watch?v=cqLhhjxch2s) from @drmichaeldouglass, with code from @alisterburt (https://github.com/BradyAJohnston/MolecularNodes/issues/157#issuecomment-1426996399).

image

Currently, this isn't coded in a way to enable easy import (hardcoded to my system), just opening the pull request with initial code that enables the import via Blender's scripting interface.

Hopefully we can get a working version to coincide with Blender 3.5's release.

## TODO

- ~~[x] Ensure that the intermediate `.vdb` file is a temporary file that is removed from the user's system afterwards.~~
- [x] Intermediate `.vdb` file has to be kept, as Blender only links to the file and doesn't save the data inside of itself.
- [x] Investigate whether scaling before or after import to Blender is better for performance
- [x] Fix ordering of XYZ / ZYX components that creates a mirroring of the density inside of blender
- [x] Create UI components to enable easier import
- [x] Create custom node groups for handling volumetric data in sensible ways
-  ~~Add support for `.mtz` electron density files from crystallography~~
-  ~~Potential for downloading directly from the EMDB via their REST api~~

This PR will no longer attempt to support `.mtz` or downloading directly from the EMDB. Potential for both in the future but keeping it limited will ensure it is all done properly.

### CODE REVIEW

**Review by drmichaeldouglass — APPROVED** [review]

**Comment by tubiana** [comment]
Just a comment on that @BradyAJohnston... Thank you so muuuuuuch  🤩

**Comment by BradyAJohnston** [comment]
Ha thanks @tubiana ! I don't really work with these datasets much myself, so if you have specific use cases / features you would like to see, please list them!

**Comment by BradyAJohnston** [comment]
I have added an initial UI in the MolecularNodes panel, so it should be easier for others to test out the branch now.

No node tree is set up, so you'll need to manually need to add the `Volume to Mesh` node.

image

image

**Comment by BradyAJohnston** [comment]
Preparing for to properly release this feature with the upcoming release of Blender 3.5.

I have now fixed the scaling problems and ordering for the XYZ / ZYX differences between blender & mrc files. The import now works reliably and also scales properly to the `world_scale` that Molecular Nodes is working on.

@alisterburt are you able to have a quick perusal over the import functions. It's all working robustly, but if there are weird things that I am maybe doing then let me know.

**Comment by BradyAJohnston** [comment]
@tubiana I have now created a beta release that includes the EM map import functionality (https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.5.0_beta).

I haven't included any custom nodes for working with the data yep, but can you give it a test drive? I have only added 3 nodes for working with it. You can style as a mesh, style as pipes and also transfer attributes from another atomistic model (such as colour of the closest atom etc).

Feedback would very much be appreciated!

**Review by alisterburt — APPROVED** [review]
This looks really clean @BradyAJohnston ! No major comments, just psyched to see what you're doing :)

**Comment by BradyAJohnston** [comment]
Takes _forever_ for the computations to finish and crashes if you try and do anything other than simple display, but it can even import large tomography maps! (import [this dataset](https://www.ebi.ac.uk/emdb/EMD-15355?tab=validation))

image
image

**Comment by alisterburt** [comment]
helllll yeah

**Comment by alisterburt** [comment]
FYI tomograms typically have inverted contrast compared to maps - high value == low density (because more electrons have been transmitted through the low density region)

**Comment by BradyAJohnston** [comment]
hahah that is very useful information to have. I was wondering why it was looking pretty garbage. 

Everything still runs super slow, but at least the features are much more obvious this way:
image

**Pull request merged**
