### PR TITLE
Biological Assembly from mmCIF

### PR DESCRIPTION
**Pull request by corredD**
Attempt for a General Support for mmCIF biological assembly. Some code extract from ePMV to create the instance mesh.
Handle cellpack cif files. I dont know if there is a performance difference between geometrynode and Instancing on Faces using the regular interface. 
Two examples : 2PLV and a cellpack model.
image
image

### CODE REVIEW

**Comment by corredD** [comment]
TODO: maybe change the quad mesh to triangle.

**Comment by BradyAJohnston** [comment]
Thanks so much for wanting to work on and improve the project! I'm excited to have you contributing. 

I won't have time to look through in detail until after Christmas, but I downloaded the fork and played around with it with some success.

## How to Handle Assemblies
This is something I have been unsure of how to handle in the past. Whether to create a new object that will become the biological assembly or change the current object (which is the asymettric unit) and then the object now becomes the biological assembly.

Certainly what I want to try and do, is keep everything inside of Geometry Nodes as much as possible. I'm unsure if there are particular performance improvements instancing inside of GN instead of on meshes. Regardless, Geometry Nodes is the current development focus of the Blender foundation and so it will be getting the biggest development focus and likely become more performant if it isn't already. 

Having the instancing occur within Geometry Nodes also enables easier manipulation of instances & geometry all without having to move between different methods of GN & regular instancing / mesh manipulation.

To handle biological assemblies for mmtf structures, I have been creating lots of nodes, each of which output a point that contains rotation and translation information. I then use those points to instance the required geometry. My implementation is lacking, as I haven't properly got it set up to handle symmetries which operate only on particular selections of chains (discussed in #109). I'm also not a huge fan of creating dozens of nodes, each of which output a single point, it seems kind of messy. @padix-key I believe is working on ensuring a common set of transformations that can be extracted via Biotite, which should also streamline biological assembly creation hopefully.

Potentially what could work is a combination of your current implementation and the current MolecularNodes implementation.

Creating an object which contains all of the information for instancing, either in the faces as you have currently done or just with points. We could use the `add_attribute()` to add the required information for chain selection, rotation matrices etc inside of attributes that are accessible inside of Geometry Nodes.
https://github.com/BradyAJohnston/MolecularNodes/blob/1c550d834734db620323eea38c0c65b6d1d550e8/MolecularNodes/load.py#L142-L151

There could then be an object which contains the transformation information for different biological assemblies, and on that object, using a Geometry Nodes node tree, we can instance the biological assembly, or this could be done inside the node tree of the original object as well.

## Parsing CellPack Files
Are you able to give more information around the parsing of CellPack files? I couldn't immediately figure out what changes you have done that enables the parsing of the files. I have a function which 'fixes' the `.cif` file so that it can be ready by Biotite, but being able to do this without having to read, write, then read the file again would be great.
https://github.com/BradyAJohnston/MolecularNodes/blob/1c550d834734db620323eea38c0c65b6d1d550e8/MolecularNodes/cellpack.py#L10-L28

Again, thanks for PR so far and excited to have your contributions, so would love your feedback on design principles and how this should best be approached.

**Comment by padix-key** [comment]
> @padix-key I believe is working on ensuring a common set of transformations that can be extracted via Biotite, which should also streamline biological assembly creation hopefully.

Yes, I am still working on it. Since I am currently also occupied with other stuff, I will probably still need some weeks until I create a PR.

**Comment by corredD** [comment]
Thanks for you comments Brady, and thanks for this great plugin.

I will try to continue to look into it in my spare time !

> Potentially what could work is a combination of your current implementation and the current MolecularNodes implementation.
> Creating an object which contains all of the information for instancing, either in the faces as you have currently done or just with points. We could use the `add_attribute()` to add the required information for chain selection, rotation matrices etc inside of attributes that are accessible inside of Geometry Nodes.
Can the attribute be a mesh object ? I would see the BU node as the "Distribute Points on Face" node but instead of using rand om or poisson disk placement it use the same approach as DupliFace. The other input would be the BU index and a selection.
 
> ## Parsing CellPack Files
> 
> Are you able to give more information around the parsing of CellPack files? I couldn't immediately figure out what changes you have done that enables the parsing of the files. I have a function which 'fixes' the `.cif` file so that it can be ready by Biotite, but being able to do this without having to read, write, then read the file again would be great.

I didn't change the cellpack files, only changed the biological unit interpretation. The problem was in the difference between the label_asym_id and auth_asym_id. label_asym_id is used in the transformation operator not the auth_asym_id which was used by default to build the molecular node. By toggling of the use_author_fields biotite will use the label_asym_id  as chain_id. Also biotite currently has a parsing error you can reproduce by trying to parse the cif file for 2PLV the operation with pdbx.convert._parse_operation_expression which I think correspond to this line : 
6 '(X0)(1-5,11-15,21-30,41-50)' A,B,C,D,E,F,G,H,I,J 

`
mol  = pdbx.get_structure(file, extra_fields = ['b_factor', 'charge'], use_author_fields=False)

def get_transformations_pdbx(file_pdbx):
    import biotite.structure.io.pdbx as pdbx
    assembly_gen_category = file_pdbx.get_category(
        "pdbx_struct_assembly_gen", expect_looped=True
    )
    struct_oper_category = file_pdbx.get_category(
        "pdbx_struct_oper_list", expect_looped=True
    )
    transformations = pdbx.convert._get_transformations(struct_oper_category)
    transform_dict = {}
    for aid, op_expr, asym_id_expr in zip(
                    assembly_gen_category["assembly_id"],
                    assembly_gen_category["oper_expression"],
                    assembly_gen_category["asym_id_list"]):
        # skip until biotite fix the issue
        if len(op_expr.split("-")) > 2:
            continue
        operations = pdbx.convert._parse_operation_expression(op_expr)
        asym_ids = asym_id_expr.split(",")
        if aid not in transform_dict:
            transform_dict[aid] = {}
        for asym in asym_ids:
            if asym not in transform_dict[aid]:
                transform_dict[aid][asym] = []
            for i, operation in enumerate(operations):
                for op_step in operation:
                    transform_dict[aid][asym].append(transformations[op_step])
    return transform_dict
`

**Pull request closed without merging**
