### PR TITLE
Support cisTEM starfiles

### PR DESCRIPTION
**Pull request by jojoelfe**
Hi,

first of all thanks so much for this fantastic work. I've long struggled to make the visualizations I want and this makes it so easy!

This PR adds support for cisTEM starfiles to the starfile branch #161 to visualize results from 2D Template Matching. I did rebase the branch to the current main branch, so it looks like a huge PR. Let me know if it would be more helpful to close and reopen in any other form.

I chose the same scaling factor as for structures (in cisTEM all coordinates are in Å) and also added one of the columns as an additional attribute.

Below is an quick example. Orientations look correct, which is expected as cisTEM uses the same convention as relion.

Again thanks for the magnificent work and I am happy to do anything to get this merged.

https://user-images.githubusercontent.com/6081039/232892820-7b32033f-75c3-427b-a29a-a02155da0725.mp4

### CODE REVIEW

**Comment by BradyAJohnston** [comment]
Thanks so much for opening the PR, and I am really happy to see someone continuing on development with the `.star` file import. I don't really have any experience with the data format so it's great to have someone who knows what they are doing with it actually work on the implementation. 

The example movie looks fantastic. I like the addition of the additional attribute for the scores also. If there are any other potential bits of data that users might want for the instances, then that can be added as well. 

I am having a bit of a hard time sifting through the large amount of diffs to ensure everything looks good. Are you able to maybe create a new branch from main as it is, add the necessary changes there (which it seems like it should only be 1 or 2 files) and then it will be easier to review. Then open a new PR with the cleaner changes.

Are you able to link me to some example datasets as well, just so that I can do some testing with it?

Again, thanks so much for working on this. Looks like it's basically ready to go into main, just need to check some things!

**Comment by jojoelfe** [comment]
> I am having a bit of a hard time sifting through the large amount of diffs to ensure everything looks good. Are you able to maybe create a new branch from main as it is, add the necessary changes there (which it seems like it should only be 1 or 2 files) and then it will be easier to review. Then open a new PR with the cleaner changes.

I pointed the PR against main. Now it is somewhat of a duplicate of #161 with my changes on top. 

> If there are any other potential bits of data that users might want for the instances, then that can be added as well.

I see no reason why one couldn't just expose every column of the starfile as an attribute. That way people have access to everything. Maybe it would pollute the attribute namespace a bit.

> Are you able to link me to some example datasets as well, just so that I can do some testing with it?

The starfile is here https://gist.github.com/jojoelfe/5bfa3edd38200b03a57bab841472714f and the molecular model is 7cpu (loaded with the center option)

If it helps, I am happy to take a shot at some of thre remaining TODO items in #161 . I think especially setting up an initial node-tree might be nice.

**Comment by BradyAJohnston** [comment]
Ah okay it's much easier to see what is going on now ha. 

>I see no reason why one couldn't just expose every column of the starfile as an attribute. That way people have access to everything. Maybe it would pollute the attribute namespace a bit.

This sounds like a good plan. Basically any column that is numeric can be added easy enough. The attributes will be limited to just the created object, so namespaces shouldn't be too much of an issue. We can think maybe about an option to select imported attributes later on. They can certainly be deleted easy enough after import.

If you want to have a go at adding a default starting node group, that would be great. Programming with nodes is particularly finicky, so let me know if I can help out.

Are these file formats ever instancing more than one protein? Or would it be a different `.star` file for each protein? If yes then we can also add an attribute for selecting specific proteins. 

I think tasks left: 
- [ ] Setup starting node tree
- [ ] potentially rename `rot` attribute
- [ ] add other numeric attributes from `.star` file on import

**Comment by jojoelfe** [comment]
This is an initial prototype. The way it now works is that after the starfile is loaded one has to select an object as the molecule input in the modifier tab:

ezgif com-optimize

Beside all the columns of the starfile two attributes are created: MOLRotations and MOLImageId. The second one is used to only show molecule locations in one image, in case locations from multiple images are contained in a starfile.

table

The nodetree looks like this:

nodetree

> Are these file formats ever instancing more than one protein? Or would it be a different `.star` file for each protein? If yes then we can also add an attribute for selecting specific proteins.

For cisTEM we are using one starfile per protein at the moment. Not sure what relion or M are doing. However, things are moving pretty fast at the moment, so who knows what will be en vogue in a few months.

There are probably some things that could be improved, such as warning when starfile or eulerangles (which I switched to from scipy as @alisterburt suggested) are not installed and having options to name the object and deciding whether one wants the default node tree. But I thought this might be good enough to get some feedback.

**Comment by BradyAJohnston** [comment]
I've had a test out and it all seems to work pretty flawlessly! For the starting node tree, I think that works great. I would maybe add a 'Simplify' checkbox. This just switches it to instancing a cube instead of a protein. That way you can turn it on and move about the scene and it performs a bit better, and you don't have to stay inside of cycles the whole time.

image

Apart from that, just changing of the `coll.mn()` and removing `tools.py` and I think it will be ready to merge. 

image

The UI is starting to get crowded, but changing that up is something that I have wanted to do anyway. Overhauling and rearranging some of that is something that I will do in a separate PR once this is merged.

**Comment by BradyAJohnston** [comment]
ping @aamelo and @alisterburt if you wanted to have a look / test and give any feedback. No worries if not!

**Review by BradyAJohnston — APPROVED** [review]

**Comment by BradyAJohnston** [comment]
All looks and works great. I like the default geometry also! I've just added a check also for `eulerangles` inside of the UI as well as `starfile`. I will likely change the UI components later, but otherwise I'm happy to merge this into main if you are happy with my minor additions!

**Comment by jojoelfe** [comment]
Yes, looks also very use-able to me, too.

I will keep on using it and make a new PR if I find issues or make improvements. Also feel free to ping me if anybody has issues.

**Comment by aamelo** [comment]
This looks great!! I'm really excited to see Blender entering the structural biology world =D. @jojoelfe I can test it and see if things are running in my system here. @BradyAJohnston Publications will have much better figures and movies from now on.

**Comment by BradyAJohnston** [comment]
@jojoelfe if you've got more demo movies as well, would love to use them to announce the new feature :)

**Comment by jojoelfe** [comment]
@BradyAJohnston feel free to use the movie above. The other things I have been playing with are rendering Phi and Psi angles as colors in microtubules:

microtubule

And visualizing the orientations of ryanodine receptors in a single-particle dataset:

rotation_small

**Pull request merged**
